apiVersion: v1
kind: Service
metadata:
  name: {{ include "castor.fullname" . }}
  labels:
    {{- include "castor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10100
      protocol: TCP
      name: http
  selector:
    {{- include "castor.selectorLabels" . | nindent 4 }}
